"""add_stripe_and_reports_tables

Revision ID: 7cb57c46a23d
Revises: 002_accounting
Create Date: 2026-02-07 14:04:19.675717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cb57c46a23d'
down_revision: Union[str, None] = '002_accounting'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_definitions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('query_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_definitions_name'), 'report_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_report_definitions_report_type'), 'report_definitions', ['report_type'], unique=False)
    op.create_index('ix_report_definitions_type', 'report_definitions', ['report_type'], unique=False)
    op.create_table('stripe_customers',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('default_payment_method', sa.String(length=100), nullable=True),
    sa.Column('stripe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stripe_customers_patient', 'stripe_customers', ['patient_id'], unique=False)
    op.create_index(op.f('ix_stripe_customers_patient_id'), 'stripe_customers', ['patient_id'], unique=True)
    op.create_index(op.f('ix_stripe_customers_stripe_customer_id'), 'stripe_customers', ['stripe_customer_id'], unique=True)
    op.create_table('stripe_payment_methods',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_exp_month', sa.Integer(), nullable=True),
    sa.Column('card_exp_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('stripe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_payment_methods_patient_id'), 'stripe_payment_methods', ['patient_id'], unique=False)
    op.create_index(op.f('ix_stripe_payment_methods_stripe_payment_method_id'), 'stripe_payment_methods', ['stripe_payment_method_id'], unique=True)
    op.create_table('report_executions',
    sa.Column('report_definition_id', sa.UUID(), nullable=False),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['report_definition_id'], ['report_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_executions_definition_date', 'report_executions', ['report_definition_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_report_executions_executed_at'), 'report_executions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_report_executions_report_definition_id'), 'report_executions', ['report_definition_id'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('report_definition_id', sa.UUID(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('execution_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['report_definition_id'], ['report_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_reports_next_run', 'scheduled_reports', ['next_run', 'is_active'], unique=False)
    op.create_index(op.f('ix_scheduled_reports_report_definition_id'), 'scheduled_reports', ['report_definition_id'], unique=False)
    op.create_table('stripe_payment_intents',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('client_secret', sa.String(length=200), nullable=True),
    sa.Column('last_payment_error', sa.Text(), nullable=True),
    sa.Column('stripe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_payment_intents_invoice_id'), 'stripe_payment_intents', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_stripe_payment_intents_patient_id'), 'stripe_payment_intents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_stripe_payment_intents_stripe_payment_intent_id'), 'stripe_payment_intents', ['stripe_payment_intent_id'], unique=True)
    op.create_table('stripe_refunds',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('stripe_refund_id', sa.String(length=100), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stripe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_refunds_payment_id'), 'stripe_refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_stripe_refunds_stripe_refund_id'), 'stripe_refunds', ['stripe_refund_id'], unique=True)
    # Commented out - these tables are managed manually with SQL, not by Alembic
    # op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    # op.drop_table('tenants')
    # op.drop_index(op.f('ix_icd10_catalog_code'), table_name='icd10_catalog')
    # op.drop_table('icd10_catalog')
    op.alter_column('accounts', 'is_detail',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('accounts', 'normal_balance',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'''debit'''::character varying"))
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('allergies', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''moderate'''::character varying"))
    op.alter_column('allergies', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'''consulta'''::character varying"))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''scheduled'''::character varying"))
    op.alter_column('appointments', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''web'''::character varying"))
    op.alter_column('charge_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('charge_items', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('charge_items', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('charge_items', 'covered_by_insurance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('charge_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''pending'''::character varying"))
    op.alter_column('clinical_notes', 'is_signed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('clinical_templates', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('clinical_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('controlled_substance_logs', 'performed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_note_lines', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('credit_note_lines', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('credit_notes', 'tax_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('credit_notes', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('credit_notes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''issued'''::character varying"))
    op.alter_column('credit_notes', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'''DO'''::character varying"))
    op.alter_column('diagnoses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('dispensations', 'dispensed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dispensations', 'patient_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('encounters', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''in_progress'''::character varying"))
    op.alter_column('encounters', 'start_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fiscal_configs', 'current_sequence',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('fiscal_configs', 'default_tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.18'))
    op.alter_column('fiscal_configs', 'tax_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''ITBIS'''::character varying"))
    op.alter_column('insurance_claims', 'total_approved',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('insurance_claims', 'total_denied',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('insurance_claims', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('insurer_contracts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('invoice_lines', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('invoice_lines', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoice_lines', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'tax_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'discount_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('invoices', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'''DO'''::character varying"))
    op.alter_column('journal_entries', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''posted'''::character varying"))
    op.drop_index(op.f('ix_journal_entries_ref'), table_name='journal_entries')
    op.alter_column('journal_entry_lines', 'debit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('journal_entry_lines', 'credit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_jel_account'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_jel_journal'), table_name='journal_entry_lines')
    op.alter_column('locations', 'location_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'''consultorio'''::character varying"))
    op.alter_column('locations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('medical_orders', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''routine'''::character varying"))
    op.alter_column('medical_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''pending'''::character varying"))
    op.alter_column('patient_insurances', 'copay_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('patient_insurances', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('patient_insurances', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('patient_problem_list', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('patients', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'''DO'''::character varying"))
    op.alter_column('patients', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('payments', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'reconciled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prescriptions', 'substitution_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('prescriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('product_lots', 'cost_per_unit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('product_lots', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_lots', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''available'''::character varying"))
    op.alter_column('products', 'unit_of_measure',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''unidad'''::character varying"))
    op.alter_column('products', 'controlled_substance_level',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'requires_cold_chain',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'requires_prescription',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('providers', 'consultation_duration_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('providers', 'max_daily_appointments',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('providers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('roles', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('schedule_templates', 'slot_duration_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('schedule_templates', 'max_overbooking',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('service_catalog', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('service_catalog', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('stock_levels', 'quantity_on_hand',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stock_levels', 'quantity_reserved',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stock_levels', 'reorder_point',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('stock_levels', 'max_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('stock_movements', 'performed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'''es'''::character varying"))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'''America/Santo_Domingo'''::character varying"))
    op.alter_column('vital_signs', 'measured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('waiting_list', 'priority',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'5'::smallint"))
    op.alter_column('waiting_list', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''waiting'''::character varying"))
    op.alter_column('warehouses', 'warehouse_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'''central'''::character varying"))
    op.alter_column('warehouses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''active'''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('warehouses', 'warehouse_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'''central'''::character varying"))
    op.alter_column('waiting_list', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''waiting'''::character varying"))
    op.alter_column('waiting_list', 'priority',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'5'::smallint"))
    op.alter_column('vital_signs', 'measured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'''America/Santo_Domingo'''::character varying"))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'''es'''::character varying"))
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('stock_movements', 'performed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_levels', 'max_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('stock_levels', 'reorder_point',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('stock_levels', 'quantity_reserved',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('stock_levels', 'quantity_on_hand',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('service_catalog', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('service_catalog', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('schedule_templates', 'max_overbooking',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('schedule_templates', 'slot_duration_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('roles', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('purchase_orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('providers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('providers', 'max_daily_appointments',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('providers', 'consultation_duration_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('products', 'requires_prescription',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'requires_cold_chain',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'controlled_substance_level',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'unit_of_measure',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''unidad'''::character varying"))
    op.alter_column('product_lots', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''available'''::character varying"))
    op.alter_column('product_lots', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_lots', 'cost_per_unit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('prescriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('prescriptions', 'substitution_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('payments', 'reconciled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('payments', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('patients', 'country',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'''DO'''::character varying"))
    op.alter_column('patient_problem_list', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('patient_insurances', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('patient_insurances', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('patient_insurances', 'copay_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('medical_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''pending'''::character varying"))
    op.alter_column('medical_orders', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''routine'''::character varying"))
    op.alter_column('locations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('locations', 'location_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'''consultorio'''::character varying"))
    op.create_index(op.f('ix_jel_journal'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_jel_account'), 'journal_entry_lines', ['account_id'], unique=False)
    op.alter_column('journal_entry_lines', 'credit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('journal_entry_lines', 'debit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_journal_entries_ref'), 'journal_entries', ['reference_type', 'reference_id'], unique=False)
    op.alter_column('journal_entries', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''posted'''::character varying"))
    op.alter_column('invoices', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'''DO'''::character varying"))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('invoices', 'discount_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'tax_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoice_lines', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoice_lines', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoice_lines', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('insurer_contracts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('insurance_claims', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''draft'''::character varying"))
    op.alter_column('insurance_claims', 'total_denied',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('insurance_claims', 'total_approved',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('fiscal_configs', 'tax_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''ITBIS'''::character varying"))
    op.alter_column('fiscal_configs', 'default_tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.18'))
    op.alter_column('fiscal_configs', 'current_sequence',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('encounters', 'start_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('encounters', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''in_progress'''::character varying"))
    op.alter_column('dispensations', 'patient_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('dispensations', 'dispensed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('credit_notes', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'''DO'''::character varying"))
    op.alter_column('credit_notes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''issued'''::character varying"))
    op.alter_column('credit_notes', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('credit_notes', 'tax_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('credit_note_lines', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('credit_note_lines', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('controlled_substance_logs', 'performed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clinical_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('clinical_templates', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('clinical_notes', 'is_signed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('charge_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''pending'''::character varying"))
    op.alter_column('charge_items', 'covered_by_insurance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('charge_items', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('charge_items', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('charge_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('appointments', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''web'''::character varying"))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''scheduled'''::character varying"))
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'''consulta'''::character varying"))
    op.alter_column('allergies', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''active'''::character varying"))
    op.alter_column('allergies', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''moderate'''::character varying"))
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'''DOP'''::character varying"))
    op.alter_column('accounts', 'normal_balance',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'''debit'''::character varying"))
    op.alter_column('accounts', 'is_detail',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # Commented out - these tables are managed manually with SQL, not by Alembic
    # op.create_table('icd10_catalog',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    # sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('icd10_catalog_pkey'))
    # )
    # op.create_index(op.f('ix_icd10_catalog_code'), 'icd10_catalog', ['code'], unique=True)
    # op.create_table('tenants',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('tenant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('schema_name', sa.VARCHAR(length=63), autoincrement=False, nullable=False),
    # sa.Column('hospital_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('country', sa.VARCHAR(length=2), server_default=sa.text("'DO'::character varying"), autoincrement=False, nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey')),
    # sa.UniqueConstraint('schema_name', name=op.f('tenants_schema_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.drop_index(op.f('ix_stripe_refunds_stripe_refund_id'), table_name='stripe_refunds')
    op.drop_index(op.f('ix_stripe_refunds_payment_id'), table_name='stripe_refunds')
    op.drop_table('stripe_refunds')
    op.drop_index(op.f('ix_stripe_payment_intents_stripe_payment_intent_id'), table_name='stripe_payment_intents')
    op.drop_index(op.f('ix_stripe_payment_intents_patient_id'), table_name='stripe_payment_intents')
    op.drop_index(op.f('ix_stripe_payment_intents_invoice_id'), table_name='stripe_payment_intents')
    op.drop_table('stripe_payment_intents')
    op.drop_index(op.f('ix_scheduled_reports_report_definition_id'), table_name='scheduled_reports')
    op.drop_index('ix_scheduled_reports_next_run', table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_report_executions_report_definition_id'), table_name='report_executions')
    op.drop_index(op.f('ix_report_executions_executed_at'), table_name='report_executions')
    op.drop_index('ix_report_executions_definition_date', table_name='report_executions')
    op.drop_table('report_executions')
    op.drop_index(op.f('ix_stripe_payment_methods_stripe_payment_method_id'), table_name='stripe_payment_methods')
    op.drop_index(op.f('ix_stripe_payment_methods_patient_id'), table_name='stripe_payment_methods')
    op.drop_table('stripe_payment_methods')
    op.drop_index(op.f('ix_stripe_customers_stripe_customer_id'), table_name='stripe_customers')
    op.drop_index(op.f('ix_stripe_customers_patient_id'), table_name='stripe_customers')
    op.drop_index('ix_stripe_customers_patient', table_name='stripe_customers')
    op.drop_table('stripe_customers')
    op.drop_index('ix_report_definitions_type', table_name='report_definitions')
    op.drop_index(op.f('ix_report_definitions_report_type'), table_name='report_definitions')
    op.drop_index(op.f('ix_report_definitions_name'), table_name='report_definitions')
    op.drop_table('report_definitions')
    # ### end Alembic commands ###
